#!/usr/bin/env bash

tmux list-sessions -F\#S -f '#{?session_attached,0,1}' |
  fzf --reverse \
    --bind 'alt-x:execute(tmux kill-session -t {})' \
    --bind 'alt-x:+reload(tmux list-sessions -F\#S -f "#{?session_attached,0,1}")' \
    --preview 'tmux list-panes -t {} -F\#D -f "#{pane_active}" | xargs tmux capture-pane -ep -t' \
    --preview-window=right:60% |
  xargs tmux switch-client -t

